# One hot encoding

In one hot encoding we divide single columsn to diffrent columns in accordance to our need.

# **Dummy Variable Trap**

Here we remove one colums generally the first one. Its always N-1 cloumns that we work on.

Its done because of multicollinerity which means in input columns there might be mathematical relation of dependence between each other columns .

# OHE using most frequent variable

Here we only keep the important columns and rest trasfer them to different columns.

In [1]:
import numpy as np
import pandas as pd

In [2]:

df = pd.read_csv('cars.csv')

In [3]:

df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [4]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [5]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [6]:
df['brand'].nunique()

32

In [7]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64


# 1. OneHotEncoding using Pandas

In [8]:

pd.get_dummies(df,columns=['fuel','owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False


# 2. K-1 OneHotEncoding

In [9]:
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True) #remove one cloumns

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

In reallife ML projects we don't use pandas for this operation because pandas doen't remember the order or the information rather we use class from sklearn named onhotencoder class which remembers the operation held.


# 3. OneHotEncoding using Sklearn

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2,random_state=2)

In [12]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [14]:
X_train.sample(6)

        brand  km_driven    fuel        owner
2332   Maruti      57000  Petrol  First Owner
6657   Toyota      90000  Diesel  First Owner
630    Maruti      80000  Diesel  First Owner
3850  Hyundai      37333  Petrol  First Owner
2858   Maruti     120000  Diesel  Third Owner
6598      BMW      70000  Diesel  Third Owner

In [15]:
X_test.sample(6)

         brand  km_driven    fuel         owner
7551     Skoda     100000  Diesel  Second Owner
4071    Maruti      60000  Diesel  Second Owner
5645      Tata     155000  Diesel   First Owner
4780   Hyundai      49900  Petrol   First Owner
6001  Mahindra      60000  Diesel   First Owner
2649   Hyundai      50000  Petrol   Third Owner

In [16]:

from sklearn.preprocessing import OneHotEncoder

In [18]:

ohe = OneHotEncoder(drop='first', sparse_output=False, dtype=np.int32)

In [19]:
X_train_new = ohe.fit_transform(X_train[['fuel','owner']])

In [20]:

X_test_new = ohe.transform(X_test[['fuel','owner']])

In [21]:

X_train_new.shape

(6502, 7)

In [22]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new))

array([['Hyundai', 35000, 1, ..., 0, 0, 0],
       ['Jeep', 60000, 1, ..., 0, 0, 0],
       ['Hyundai', 25000, 0, ..., 0, 0, 0],
       ...,
       ['Tata', 15000, 0, ..., 0, 0, 0],
       ['Maruti', 32500, 1, ..., 1, 0, 0],
       ['Isuzu', 121000, 1, ..., 0, 0, 0]], dtype=object)

In [23]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new)).shape

(6502, 9)


# 4. OneHotEncoding with Top Categories

In [24]:

counts = df['brand'].value_counts()

In [25]:

df['brand'].nunique()
threshold = 100

In [26]:

repl = counts[counts <= threshold].index

In [27]:
pd.get_dummies(df['brand'].replace(repl, 'uncommon')).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
1534,False,False,False,True,False,False,False,False,False,False,False,False,False
5326,False,False,False,False,False,False,True,False,False,False,False,False,False
6589,False,False,False,True,False,False,False,False,False,False,False,False,False
5259,True,False,False,False,False,False,False,False,False,False,False,False,False
2532,False,False,False,False,False,False,False,False,False,False,False,False,True